/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.casinocsgo;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    JButton detener1 = new JButton("Detener");
    JButton detener2 = new JButton("Detener");
    JButton detener3 = new JButton("Detener");
    JButton iniciar = new JButton("Iniciar");
    JButton detenerTodo = new JButton("Detener Todo");
    public static String img1="ak47.png",img2="beretas.png",img3="karambit.png";
    public static JLabel uno = new JLabel();
    public static JLabel dos = new JLabel();
    public static JLabel tres = new JLabel();
    JPanel controles = new JPanel();
    JPanel imagenes = new JPanel();
    Imagen1 hilo1 = new Imagen1();
    Imagen2 hilo2 = new Imagen2();
    Imagen3 hilo3 = new Imagen3();
    int z=0;
    
    public Interfaz(){
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        uno.setIcon(new ImageIcon(img1));
        dos.setIcon(new ImageIcon(img2));
        tres.setIcon(new ImageIcon(img3));
        imagenes.setLayout(new FlowLayout());
        imagenes.add(uno);
        imagenes.add(dos);
        imagenes.add(tres);
        controles.setLayout(new GridLayout(2,3));
        controles.add(detener1);
        controles.add(detener2);
        controles.add(detener3);
        controles.add(iniciar);
        controles.add(detenerTodo);
        add("Center",imagenes);
        add("South",controles);
//Controles
        iniciar.addActionListener(new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent evt){
        if(hilo1.isAlive() == false){
            if(hilo2.isAlive() == false){
                if(hilo3.isAlive() == false){
                    hilo1 = new Imagen1();
                    hilo2 = new Imagen2();
                    hilo3 = new Imagen3();
                    hilo1.activo=true;
                    hilo2.activo=true;
                    hilo3.activo=true;
                    hilo1.start();
                    hilo2.start();
                    hilo3.start();
                    z=1;
                }
            }
        }
    }
});
        detenerTodo.addActionListener(new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent evt){
        if(z==1){
            hilo1.activo=false;
            hilo2.activo=false;
            hilo3.activo=false;
                if(hilo1.c==hilo2.c){
                    if(hilo2.c==hilo3.c){
                        JOptionPane.showMessageDialog(Interfaz.this," Ganador ! ! ! ");
                }
            }
        }
    }
});
        detener1.addActionListener(new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent evt){
        hilo1.activo=false;
    }
});
        detener2.addActionListener(new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent evt){
        hilo2.activo=false;
    }
});
        detener3.addActionListener(new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent evt){
        hilo3.activo=false;
    }
});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
